language: python
pyton:
 - "2.7"

install: "pip install -r requirements.txt"

before_script:
 - autopep8 -ir *.py
 - flake8 --max-complexity=6 --exclude=*.txt,*.md --max-line-length=100 *

script:
 - lettuce test/
 - python test/TestCalculator.py -v
 - coverage run --branch test/TestCalculator.py
 - coverage report -m

notifications:
 - email:false
